spring:
  application:
    name: HMPT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pt
    username: root
    password: csqszq
  servlet:
    multipart:
      #配置单个文件最大上传大小
      max-file-size: 10MB
      #配置单个请求最大上传大小(一次请求可以上传多个文件)
      max-request-size: 100MB
#    type: org.apache.ibatis.datasource.pooled.PooledDataSource
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰式命名规则
    map-underscore-to-camel-case: true

minio:
  endpoint: https://127.0.0.1:9000/
  accessKey: 1GfxsoIpxnHovynsf13R
  secretKey: Qb1EPjGKlJWMsPCIArIQvMYWJT9a4Xlw1z9IIpEu
  bucketName: test1




  #mybatis:
#  type-aliases-package: org.qqhru.humt.entity
#  mapper-locations: classpath:mapper/**
#  configuration:
#    map-underscore-to-camel-case: true
#
##server:
##  port: 8085
#
## key value
#username: zhangsan
#password: 1234
#
#user:
#  name: jack
#  password: 1111
#  age: 18
#
#cityList:
##   table - value
#  - shangHai
#  - Beijing
#  - TianJin
#
#
#

